#!/usr/bin/env python3
"""Diff a LaTeX draft against a venue profile (stdlib only, offline).

Compares the draft's documentclass/options, keyword blocks, abstract length,
author block, and required sections against a venues/conferences/<id>.yml
profile (family-merged), for one chosen track. Emits a Markdown gap report
the tailor-to-venue skill turns into a tailoring plan.

This script checks FACTS it can detect deterministically. It does not
rewrite anything, and its report always starts with an instruction to
re-verify the profile against the live CFP — profiles go stale.

Usage:
    python3 venue_diff.py <main.tex> --venue <profile.yml> [--track NAME]

Exit codes: 0 report produced, 2 bad input (missing file, unknown track,
unparseable profile).
"""

import argparse
import os
import re
import sys

import texscan
import venueyaml

SCRIPT_DIR = os.path.relpath(os.path.dirname(os.path.abspath(__file__)))

DOCCLASS_RE = re.compile(r"\\documentclass\s*(?:\[([^\]]*)\])?\s*\{([^}]+)\}")

# Detectors for profile `required_sections` ids → (regex, human label).
SECTION_DETECTORS = {
    "ccs-concepts": (r"\\begin\{CCSXML\}|\\ccsdesc", "ACM CCS concepts (\\ccsdesc / CCSXML block)"),
    "keywords": (r"\\keywords\s*\{|\\begin\{IEEEkeywords\}|\\keyword\s*\{", "author keywords block"),
    "acm-reference-format": (None, "ACM reference format block (auto-generated by acmart — verify it renders in the PDF)"),
    "ieee-index-terms": (r"\\begin\{IEEEkeywords\}", "IEEE Index Terms (\\begin{IEEEkeywords})"),
    "neurips-checklist": (r"(?i)\\section\*?\{\s*NeurIPS\s+Paper\s+Checklist|\\answerYes|\\answerNo", "NeurIPS paper checklist"),
    "icml-impact-statement": (r"(?i)\\section\*?\{\s*Impact\s+Statement", "ICML impact statement section"),
    "ai-use-acknowledgement": (r"(?i)(ai-?generated\s+content\s+acknowledg|generative\s+ai\b.{0,80}(disclos|acknowledg))", "AI-generated-content acknowledgement"),
    "coi-declaration": (None, "conflict-of-interest declaration (usually entered in the submission system — check manually)"),
    "acknowledgments": (r"\\begin\{acks\}|\\section\*?\{\s*Acknowledg|\\acknowledgments", "acknowledgments section"),
}

ANON_NAME_HINT = re.compile(r"(?i)anonym|blinded|omitted for review|anonymous author")


def fail(msg):
    sys.stderr.write("error: %s\n" % msg)
    sys.exit(2)


def parse_docclass(text):
    m = DOCCLASS_RE.search(text)
    if not m:
        return None, set()
    opts = {o.strip() for o in (m.group(1) or "").split(",") if o.strip()}
    return m.group(2).strip(), opts


def pick_track(profile, name):
    tracks = profile.get("tracks") or []
    if not tracks:
        fail("profile has no tracks; fix the venue YAML or pass facts manually")
    if name is None:
        return tracks[0], ("note: no --track given; defaulting to %r. "
                           "Available: %s" % (tracks[0].get("name"),
                                              ", ".join(t.get("name", "?") for t in tracks)))
    for t in tracks:
        if t.get("name", "").lower() == name.lower():
            return t, None
    fail("track %r not in profile. Available tracks: %s"
         % (name, ", ".join(t.get("name", "?") for t in tracks)))


def get(profile, *keys):
    cur = profile
    for k in keys:
        if not isinstance(cur, dict) or k not in cur or cur[k] is None:
            return None
        cur = cur[k]
    return cur


def abstract_words(text):
    m = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", text, re.DOTALL)
    if not m:
        return None
    return len(texscan.plain_words(m.group(1)))


def author_block_status(text):
    """Return (found, looks_anonymous, sample)."""
    pats = [r"\\author\s*(?:\[[^\]]*\])?\s*\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}",
            r"\\IEEEauthorblockN\s*\{([^}]*)\}"]
    for p in pats:
        m = re.search(p, text, re.DOTALL)
        if m:
            content = re.sub(r"\\[A-Za-z]+", " ", m.group(1))
            content = re.sub(r"\s+", " ", content).strip()
            if not content:
                return True, True, ""
            return True, bool(ANON_NAME_HINT.search(content)), content[:80]
    return False, False, None


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Diff a LaTeX draft against a venue profile and print a "
        "Markdown gap report (template, options, required sections, abstract, "
        "author block, page-limit context).")
    parser.add_argument("main_tex", help="main .tex file of the draft")
    parser.add_argument("--venue", required=True,
                        help="path to venues/conferences/<id>.yml")
    parser.add_argument("--track", default=None,
                        help="track name as listed in the profile (e.g. Research, Demo)")
    parser.add_argument("--no-family", action="store_true",
                        help="do not merge the venue family profile")
    args = parser.parse_args(argv)

    try:
        profile = (venueyaml.load(args.venue) if args.no_family
                   else venueyaml.load_with_family(args.venue))
    except venueyaml.VenueYamlError as exc:
        fail(str(exc))
    try:
        text, files, warnings = texscan.read_tex(args.main_tex)
    except texscan.TexScanError as exc:
        fail(str(exc))

    track, track_note = pick_track(profile, args.track)
    lines = []
    add = lines.append

    add("# Venue diff: %s -> %s [%s]"
        % (args.main_tex, profile.get("id", args.venue), track.get("name", "?")))
    add("")
    cfp = profile.get("cfp_url") or "(no cfp_url in profile)"
    verified = get(profile, "verified", "date") or "unknown"
    confidence = get(profile, "verified", "confidence") or "unknown"
    add("> **VERIFY BEFORE TRUSTING:** profile last verified %s (%s)."
        % (verified, confidence))
    add("> Re-check page limits, deadlines, template, and blind level against the live CFP:")
    add("> %s" % cfp)
    add("")
    if track_note:
        add("_%s_" % track_note)
        add("")
    for w in warnings:
        add("_warning: %s_" % w)
    if warnings:
        add("")

    # --- template / documentclass --------------------------------------
    add("## Template / documentclass")
    add("")
    found_class, found_opts = parse_docclass(text)
    want_invocation = get(profile, "format", "documentclass") or ""
    want_class, want_opts = parse_docclass(want_invocation)
    add("| | draft | venue profile |")
    add("|---|---|---|")
    add("| class | `%s` | `%s` |" % (found_class or "NOT FOUND",
                                     want_class or want_invocation or "unspecified"))
    add("| options | `%s` | `%s` |" % (",".join(sorted(found_opts)) or "(none)",
                                       ",".join(sorted(want_opts)) or "(none)"))
    add("")
    if found_class is None:
        add("- [GAP] no \\documentclass found in the resolved sources.")
    elif want_class and found_class != want_class:
        add("- [GAP] template switch required: `%s` -> `%s`. "
            "See references/template-switching.md." % (found_class, want_class))
    elif want_class:
        add("- [OK] document class matches.")
        missing = want_opts - found_opts
        extra = found_opts - want_opts
        if missing:
            add("- [GAP] missing class options: `%s`." % ",".join(sorted(missing)))
        if extra:
            add("- [CHECK] extra class options not in profile: `%s` "
                "(drop camera-ready/preprint flags for submission)." % ",".join(sorted(extra)))
        if not missing and not extra:
            add("- [OK] class options match the profile invocation.")
    template = get(profile, "format", "template")
    columns = get(profile, "format", "columns")
    if template:
        add("- venue template family: `%s`%s."
            % (template, (", %s-column" % columns) if columns else ""))
    add("")

    # --- page budget context --------------------------------------------
    add("## Page budget (track: %s)" % track.get("name", "?"))
    add("")
    limit = track.get("page_limit")
    excludes = track.get("page_limit_excludes") or []
    if limit is None:
        add("- profile lists NO hard page limit for this track; check the CFP notes:")
    else:
        add("- limit: **%s pages**, excluding: %s."
            % (limit, ", ".join(excludes) if excludes else "NOTHING (references count!)"))
    if track.get("notes"):
        add("- profile notes: %s" % str(track["notes"]).strip())
    add("- run `python3 %s/page_budget.py %s --venue %s --track %r` "
        "for the section-by-section cutting plan." % (SCRIPT_DIR, args.main_tex,
                                                      args.venue, track.get("name", "")))
    other = [t for t in (profile.get("tracks") or []) if t is not track]
    if other:
        add("- other tracks at this venue (for repositioning — see "
            "references/contribution-reframing.md):")
        for t in other:
            lim = t.get("page_limit")
            exc = t.get("page_limit_excludes") or []
            lim_str = ("%s pages" % lim) if lim is not None else "no fixed page limit"
            add("  - %s: %s%s" % (t.get("name", "?"), lim_str,
                                  " excl. " + ", ".join(exc) if exc else ""))
    add("")

    # --- blind level / author block --------------------------------------
    add("## Blind level / author block")
    add("")
    blind = get(profile, "review", "blind") or "unspecified"
    found, looks_anon, sample = author_block_status(text)
    add("- venue blind level: **%s**." % blind)
    if blind in ("double", "triple"):
        if "anonymous" in (want_opts or set()) and found_class and "anonymous" not in found_opts:
            add("- [GAP] profile invocation uses `anonymous` but the draft does not set it.")
        if found and not looks_anon:
            add("- [GAP] author block appears to contain real names (`%s...`) — "
                "must be anonymized." % sample)
        elif found and looks_anon:
            add("- [OK] author block looks anonymized.")
        else:
            add("- [CHECK] no author block detected; confirm the template hides it correctly.")
        add("- run `python3 %s/anon_sweep.py %s --level %s` for the full leak scan "
            "(acknowledgments, repo links, self-citations, PDF metadata)."
            % (SCRIPT_DIR, args.main_tex, blind))
    elif blind == "single":
        if found and looks_anon:
            add("- [GAP] venue is single-blind (authors must be LISTED) but the author "
                "block looks like an anonymization placeholder — restore names.")
        elif found:
            add("- [OK] authors are listed, as required for single-blind review.")
        else:
            add("- [GAP] no author block found; single-blind venues require names "
                "and affiliations on the submission.")
    else:
        add("- [CHECK] blind level unspecified in profile — confirm on the CFP.")
    add("")

    # --- abstract ---------------------------------------------------------
    add("## Abstract")
    add("")
    wc = abstract_words(text)
    want_range = get(profile, "format", "abstract_words")
    if wc is None:
        add("- [GAP] no abstract environment found.")
    elif isinstance(want_range, list) and len(want_range) == 2:
        lo, hi = want_range
        verdict = "OK" if lo <= wc <= hi else "GAP"
        add("- [%s] abstract is %d words; venue norm is %s-%s." % (verdict, wc, lo, hi))
    else:
        add("- abstract is %d words; profile sets no limit (150-250 is the common norm)." % wc)
    add("")

    # --- required sections -------------------------------------------------
    add("## Required sections / blocks")
    add("")
    required = get(profile, "format", "required_sections") or []
    if not required:
        add("- profile lists no required sections; check the CFP for checklists "
            "or mandatory statements.")
    for req in required:
        det = SECTION_DETECTORS.get(str(req))
        if det is None:
            add("- [CHECK] `%s`: no automatic detector — verify manually against the CFP." % req)
        elif det[0] is None:
            add("- [CHECK] `%s`: %s." % (req, det[1]))
        elif re.search(det[0], text):
            add("- [OK] `%s`: found (%s)." % (req, det[1]))
        else:
            add("- [GAP] `%s`: NOT found — add %s." % (req, det[1]))
    add("")

    # --- venue facts for the plan ------------------------------------------
    add("## Venue facts to carry into the plan")
    add("")
    facts = [
        ("submission system", get(profile, "review", "submission_system")),
        ("submission URL", get(profile, "review", "submission_url")),
        ("rebuttal format", get(profile, "review", "rebuttal_format")),
        ("camera-ready rail", get(profile, "camera_ready", "rail")),
        ("abstract deadline", get(profile, "deadlines", "abstract")),
        ("paper deadline", get(profile, "deadlines", "paper")),
        ("deadline timezone", get(profile, "deadlines", "timezone")),
    ]
    for label, val in facts:
        if val is not None:
            add("- %s: %s" % (label, val))
    llm = get(profile, "review", "llm_policy")
    if llm:
        add("- LLM/AI-use policy (profile summary): %s" % str(llm).strip()[:300])
    add("")
    add("_Generated by venue_diff.py — deterministic signals only. The compiled "
        "PDF and the live CFP are ground truth._")

    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
