#!/usr/bin/env python3
"""Required-sections checker for LaTeX submissions.

Verifies every entry in the venue profile's format.required_sections is
present in the source — NeurIPS paper checklist, ICML impact statement,
ICDE-style AI-use acknowledgement, COI declarations, ACM CCS concepts and
keywords — plus baseline structure (title, abstract, bibliography).

Usage:
    python3 check_sections.py paper.tex --venue venues/conferences/neurips-2026.yml

Exit codes: 0 clean (or warnings without --strict), 1 ERROR findings, 2 failure.
"""
from __future__ import annotations

import re
import sys

import texlib
from texlib import Finding


def _section_titles(doc: texlib.TexDoc):
    """All \\section/\\section*/\\subsection titles -> (pos, title)."""
    out = []
    for cmd in ("section", "section*", "subsection", "subsection*", "paragraph"):
        for pos, _opt, arg in doc.find_commands(cmd):
            if arg:
                out.append((pos, arg))
    return out


def _has_section(doc, pattern: str) -> bool:
    rex = re.compile(pattern, re.I)
    return any(rex.search(title) for _pos, title in _section_titles(doc))


# Each detector: doc -> (present: bool, detail: str)
def _det_neurips_checklist(doc):
    if re.search(r"\\answer(?:Yes|No|NA|TODO)\b", doc.text):
        return True, "checklist answer macros found"
    if _has_section(doc, r"(neurips\s+)?paper\s+checklist|^checklist$"):
        return True, "checklist section found"
    return False, ("mandatory NeurIPS paper checklist not found (no \\answerYes/"
                   "\\answerNo/\\answerNA macros, no checklist section) — "
                   "omitting it is an explicit desk-reject")


def _det_impact_statement(doc):
    if _has_section(doc, r"impact\s+statement|broader\s+impact"):
        return True, "impact statement section found"
    return False, "mandatory Impact Statement section not found (ICML places it after acknowledgements, before references; excluded from the page limit)"


def _det_ai_ack(doc):
    if _has_section(doc, r"(ai|llm|generative).{0,30}(acknowledg|disclosure|statement)|acknowledg.{0,30}(ai|llm|generative)"):
        return True, "AI-use acknowledgement section found"
    if re.search(r"AI-?Generated Content Acknowledg", doc.text, re.I):
        return True, "AI-generated-content acknowledgement text found"
    return False, ("mandatory AI-use acknowledgement not found — e.g. ICDE requires "
                   "an 'AI-Generated Content Acknowledgement' naming the AI system "
                   "and affected sections; missing it risks desk reject")


def _det_coi(doc):
    if _has_section(doc, r"conflicts?\s+of\s+interest|competing\s+interests"):
        return True, "COI section found"
    return False, ("no conflict-of-interest declaration found in the paper — NOTE: "
                   "many venues collect COI in the submission system (CMT/OpenReview "
                   "forms) rather than in the PDF; verify where this venue wants it")


def _det_ccs(doc):
    has_xml = bool(doc.env_spans("CCSXML"))
    has_desc = bool(doc.find_commands("ccsdesc"))
    if has_xml and has_desc:
        return True, "CCSXML block and \\ccsdesc found"
    missing = [n for n, ok in (("\\begin{CCSXML}", has_xml), ("\\ccsdesc", has_desc)) if not ok]
    return False, (f"ACM CCS concepts incomplete: missing {' and '.join(missing)} — "
                   "generate both with the ACM CCS tool (dl.acm.org/ccs)")


def _det_keywords(doc):
    for _pos, _opt, arg in doc.find_commands("keywords"):
        if arg and arg.strip():
            return True, "\\keywords found"
    if doc.env_spans("IEEEkeywords"):
        return True, "IEEEkeywords environment found"
    return False, "no \\keywords{...} (or IEEEkeywords environment) found"


def _det_acm_ref_format(doc):
    m = re.search(r"printacmref\s*=\s*false", doc.text)
    if m:
        return True, ("\\settopmatter{printacmref=false} found — acceptable for "
                      "review at some venues, but the ACM reference block MUST "
                      "render in the camera-ready")
    return True, "ACM reference format block is auto-generated by acmart"


def _det_ethics(doc):
    if _has_section(doc, r"ethics\s+statement"):
        return True, "ethics statement found"
    return False, "no Ethics Statement section (optional at most venues that list it)"


def _det_reproducibility(doc):
    if _has_section(doc, r"reproducibility"):
        return True, "reproducibility statement found"
    return False, "no Reproducibility Statement section (optional at most venues that list it)"


def _det_llm_disclosure(doc):
    if _has_section(doc, r"(llm|language\s+model).{0,30}(usage|use|disclosure)"):
        return True, "LLM-usage disclosure section found"
    return False, "no LLM-usage disclosure section found"


# token -> (detector, severity-if-missing)
_DETECTORS = {
    "neurips-checklist": (_det_neurips_checklist, "ERROR"),
    "icml-impact-statement": (_det_impact_statement, "ERROR"),
    "impact-statement": (_det_impact_statement, "ERROR"),
    "ai-use-acknowledgement": (_det_ai_ack, "ERROR"),
    "ai-generated-content-acknowledgement": (_det_ai_ack, "ERROR"),
    "coi-declaration": (_det_coi, "WARN"),
    "ccs-concepts": (_det_ccs, "ERROR"),
    "keywords": (_det_keywords, "ERROR"),
    "acm-reference-format": (_det_acm_ref_format, "INFO"),
    "ethics-statement": (_det_ethics, "INFO"),
    "reproducibility-statement": (_det_reproducibility, "INFO"),
    "llm-usage-disclosure": (_det_llm_disclosure, "ERROR"),
}


def collect(doc: texlib.TexDoc, profile: dict, track: dict | None, args) -> list[Finding]:
    findings: list[Finding] = []
    fmt = profile.get("format") or {}
    required = fmt.get("required_sections") or []

    def add(sev, check, msg, pos=None):
        if pos is not None:
            f, ln = doc.loc(pos)
        else:
            f, ln = args.tex, None
        findings.append(Finding(sev, check, f, ln, msg))

    # baseline structure
    if not doc.env_spans("abstract") and not doc.find_commands("abstract"):
        add("ERROR", "sections/abstract-missing", "no abstract found "
            "(\\begin{abstract} or \\abstract{...})")
    if not any(arg for _p, _o, arg in doc.find_commands("title") if arg and arg.strip()):
        add("ERROR", "sections/title-missing", "no \\title{...} found")
    has_bib = bool(
        re.search(r"\\bibliography\s*\{|\\printbibliography|\\begin\{thebibliography\}", doc.text)
    )
    if not has_bib:
        add("WARN", "sections/bibliography-missing",
            "no bibliography found (\\bibliography{}, \\printbibliography, or "
            "thebibliography) — submitting without references is desk-reject bait")

    # profile-required sections
    for token in required:
        norm = str(token).split()[0].strip().lower()
        det = _DETECTORS.get(norm)
        if det is None:
            add("INFO", f"sections/manual:{norm}",
                f"profile requires '{token}' but no automated detector exists — "
                f"verify by hand against the CFP: {profile.get('cfp_url')}")
            continue
        fn, sev = det
        present, detail = fn(doc)
        if present:
            add("INFO", f"sections/present:{norm}", detail)
        else:
            add(sev, f"sections/missing:{norm}", detail)

    if not required:
        add("INFO", "sections/none-required",
            "profile lists no required sections — verify the live CFP, since "
            "venues add new mandatory statements year to year")
    return findings


def main() -> int:
    return texlib.run_checker("check_sections", __doc__.splitlines()[0], collect)


if __name__ == "__main__":
    sys.exit(main())
